// Generated by CIRCT firtool-1.139.0
`ifndef layers_core_top_Verification
  `define layers_core_top_Verification
  bind core_top core_top_Verification verification ();
`endif // not def layers_core_top_Verification
