// Generated by CIRCT firtool-1.139.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module mycpu_top_Verification();
  reg [31:0] timer_cnt;
  `ifndef SYNTHESIS
    always @(posedge mycpu_top.aclk) begin
      if ((`PRINTF_COND_) & timer_cnt < 32'h14 & ~mycpu_top.reset_high) begin
        $fwrite(32'h80000002, "--- Cycle %d ---\n", timer_cnt);
        $fwrite(32'h80000002, "IF_REQ:  valid=%d, addr=0x%x\n",
                mycpu_top.icache_io_cpu_valid, mycpu_top.icache_io_cpu_index);
        $fwrite(32'h80000002, "AXI_AR:  arvalid=%d, arready=%d, araddr=0x%x\n",
                mycpu_top.arvalid, mycpu_top.arready, mycpu_top.araddr);
        $fwrite(32'h80000002, "AXI_R:   rvalid=%d, rready=%d, rdata=0x%x\n",
                mycpu_top.rvalid, mycpu_top.rready, mycpu_top.rdata);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge mycpu_top.aclk or posedge mycpu_top.reset_high) begin
    if (mycpu_top.reset_high)
      timer_cnt <= 32'h0;
    else
      timer_cnt <= timer_cnt + 32'h1;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      if (mycpu_top.reset_high)
        timer_cnt = 32'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
endmodule

