# SET PROJECT NAME
set project_name loongson
set project_path ./project
set project_part xc7a200tfbg676-2

# CLEAR
# This intentionally rebuilds the generated Vivado project.  Save any GUI-only
# waveform/layout changes before running it.
file delete -force $project_path
file delete -force ../../../chip/soc_demo/nscscc-team/xilinx_ip/clk_pll/gen
file delete -force ../../../chip/soc_demo/nscscc-team/xilinx_ip/clk_pll_ddr/gen
file delete -force ../../../chip/soc_demo/nscscc-team/xilinx_ip/vio/gen
file delete -force ../../../chip/soc_demo/nscscc-team/xilinx_ip/axi_crossbar_2x3/gen
file delete -force ../../../chip/soc_demo/nscscc-team/xilinx_ip/jtag_axi/gen
file delete -force ../../../chip/soc_demo/nscscc-team/xilinx_ip/mig_axi_32/gen

create_project -force $project_name $project_path -part $project_part

# Add conventional sources
add_files -scan_for_includes ../../../chip/soc_demo/nscscc-team
add_files -scan_for_includes ../../../IP/AXI_SRAM_BRIDGE
add_files -scan_for_includes ../../../IP/APB_DEV/URT
add_files -norecurse "../../../IP/APB_DEV/apb_dev_top_no_nand.v"
add_files -norecurse "../../../IP/APB_DEV/apb_mux2.v"
add_files -norecurse "../../../IP/AMBA/axi2apb.v"

# Add SoC IPs
add_files -quiet [glob -nocomplain ../../../chip/soc_demo/nscscc-team/xilinx_ip/*/*.xci]

# Add simulation files
add_files -fileset sim_1 ../testbench

# Add only the generated CPU RTL files from the CPU root.  Do not recursively
# scan xilinx_ip output-product directories: their VHDL libraries are owned by
# the two XCI objects below.
set mycpu_root [file normalize "../../../IP/myCPU"]
set mycpu_rtl [concat \
    [glob -nocomplain "$mycpu_root/*.sv"] \
    [glob -nocomplain "$mycpu_root/*.v"]]
if {[llength $mycpu_rtl] == 0} {
    error "No generated CPU RTL found under $mycpu_root"
}
add_files -norecurse $mycpu_rtl

# multiplier and div_gen_0 are separate Vivado-native IPs.
set mycpu_xci [glob -nocomplain "$mycpu_root/xilinx_ip/*/*.xci"]
set mycpu_xcix [glob -nocomplain "$mycpu_root/xilinx_ip/*/*.xcix"]
if {[llength $mycpu_xci] != 2} {
    error "Expected exactly two myCPU XCI files (multiplier and div_gen_0), got [llength $mycpu_xci]"
}
add_files -quiet $mycpu_xci
add_files -quiet $mycpu_xcix

# Upgrade legacy SoC IPs if needed.  The native arithmetic IPs generated by the
# matching Vivado release remain unlocked.
upgrade_ip -quiet [get_ips]

# Add constraints
add_files -fileset constrs_1 -quiet ../constraints

set_property top soc_top [current_fileset]
set_property top tb_top [get_filesets sim_1]
set_property xsim.simulate.log_all_signals true [get_filesets sim_1]
set_property strategy Flow_PerfOptimized_high [get_runs synth_1]
set_property strategy Performance_Explore [get_runs impl_1]
